### ISSUE TITLE
updating theme path...init.sh: 159: init.sh: Bad substitution

### ISSUE THREAD

**Issue by djoudi** [zkoss/atlantic#134]
sh init.sh

This script will assist you in setting up your custom ZK theme maven project.

Enter the [GROUP ID] for your theme project and press [ENTER]: org.zkoss.theme
Enter the [ARTIFACT ID] (will also be your theme name) for your theme project and press [ENTER]: dreamdev
Enter the [VERSION] for your theme project and press [ENTER]: 8.6.1
Enter the [DISPLAY NAME] for your theme and press [ENTER]: erp

GROUP ID     : org.zkoss.theme
ARTIFACT ID  : erp
VERSION      : 8.6.1
DISPLAY NAME : ERP

Is the above information correct? [Y/n] Y
updating pom.xml......................done.
updating version......................done.
updating Version.java.................done.
updating ThemeWebAppInit.java.........done.
updating theme path...init.sh: 159: init.sh: Bad substitution

updating theme path...init.sh: 159: init.sh: Bad substitution

**Comment by cor3000** [comment]
The init script has already been executed for atlantic theme, it doesn't need to run again:
If you're planning to build a custom theme please start using the [zkthemetemplate](https://github.com/zkoss/zkThemeTemplate).
